
package util;

import java.io.Serializable;


public enum Operation {

    OPERATION_LOGIN,
    OPERATION_SVI_AUTORI,
    OPERATION_SACUVAJ_RADNIKA,
    OPERATION_SACUVAJ_KNJIGU,
    OPERATION_SACUVAJ_CLANA,
    OPERATION_PRETRAGA_KNJIGA,
    OPERATION_SVI_CLANOVI,
    OPERATION_SACUVAJ_ZADUZENJE,
    OPERATION_SVA_ZADUZENJA,
    OPERATION_VRATI_KNJIGU,
    OPERATION_SVE_KNJIGE,
    BRISANJE_KNJIGE;

}
